# Form implementation generated from reading ui file 'c:\Users\Zangara\Documents\1-CURSO AX\8460 - TÉCNICAS AVANZADAS DE PROGRAMACIÓN\BBDD\.vscode\LaSegura\SegurosLaGallega\CapaVista\ventanaPpal.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(589, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 589, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuCRUD_AUTOS = QtWidgets.QMenu(self.menubar)
        self.menuCRUD_AUTOS.setObjectName("menuCRUD_AUTOS")
        self.menuCrud_Personas = QtWidgets.QMenu(self.menubar)
        self.menuCrud_Personas.setObjectName("menuCrud_Personas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSalir = QtGui.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAutos = QtGui.QAction(MainWindow)
        self.actionAutos.setObjectName("actionAutos")
        self.actionPersonas = QtGui.QAction(MainWindow)
        self.actionPersonas.setObjectName("actionPersonas")
        self.actionSiniestros = QtGui.QAction(MainWindow)
        self.actionSiniestros.setObjectName("actionSiniestros")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuCRUD_AUTOS.addAction(self.actionAutos)
        self.menuCrud_Personas.addAction(self.actionPersonas)
        self.menuCrud_Personas.addSeparator()
        self.menuCrud_Personas.addAction(self.actionSiniestros)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuCRUD_AUTOS.menuAction())
        self.menubar.addAction(self.menuCrud_Personas.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sistema de Gestion de Seguros \"La Segura\""))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuCRUD_AUTOS.setTitle(_translate("MainWindow", "CRUD AUTOS"))
        self.menuCrud_Personas.setTitle(_translate("MainWindow", "Crud Personas"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAutos.setText(_translate("MainWindow", "Autos"))
        self.actionPersonas.setText(_translate("MainWindow", "Personas"))
        self.actionSiniestros.setText(_translate("MainWindow", "Siniestros"))
